name: Build NGINX Tarball on CentOS 8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This is fine since we'll use Docker

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          echo "Using Docker to run CentOS 8"
      
      - name: Build NGINX in Docker
        uses: docker://centos:8
        with:
          args: |
            /bin/bash -c "
            yum install -y epel-release &&
            yum install -y gcc make pcre-devel zlib-devel openssl-devel tar &&
            curl -O http://nginx.org/download/nginx-1.20.1.tar.gz &&
            tar -xvf nginx-1.20.1.tar.gz &&
            cd nginx-1.20.1 &&
            ./configure --prefix=/usr --with-http_ssl_module --with-http_v2_module &&
            make &&
            make install DESTDIR=/nginx-install &&
            cd /nginx-install &&
            tar -czvf nginx-1.20.1.tar.gz ."

      - name: Upload NGINX tar.gz package
        uses: actions/upload-artifact@v3
        with:
          name: nginx-tarball
          path: nginx-install/nginx-1.20.1.tar.gz
