name: Build Nginx for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        choco install strawberryperl nasm -y
        choco install wget -y
        choco install make -y

    - name: Download Nginx Source and Dependencies
      run: |
        wget http://nginx.org/download/nginx-1.23.0.tar.gz
        tar -zxvf nginx-1.23.0.tar.gz
        wget https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.zip -O pcre-8.45.zip
        wget https://zlib.net/zlib1211.zip -O zlib-1.2.11.zip
        wget https://www.openssl.org/source/openssl-1.1.1l.tar.gz
        tar -zxvf openssl-1.1.1l.tar.gz
        tar -xf pcre-8.45.zip
        tar -xf zlib-1.2.11.zip

    - name: Compile Nginx for Windows with Makefile
      run: |
        cd nginx-1.23.0
        make -f Makefile.win PCRE=../pcre-8.45 ZLIB=../zlib-1.2.11 OPENSSL=../openssl-1.1.1l

    - name: Archive Nginx Binary
      run: |
        tar -czvf nginx-windows.tar.gz objs/nginx.exe conf
      continue-on-error: true

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nginx-windows
        path: nginx-windows.tar.gz
