name: Build NGINX RPM on CentOS 8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm mock

      - name: Set up mock configuration for CentOS 8
        run: |
          sudo usermod -a -G mock $USER
          echo "config_opts['target_arch'] = 'x86_64'" | sudo tee -a /etc/mock/default.cfg
          echo "config_opts['dist'] = 'el8'" | sudo tee -a /etc/mock/default.cfg
          sudo mock -r epel-8-x86_64 --init

      - name: Prepare NGINX source
        run: |
          curl -O http://nginx.org/download/nginx-1.20.1.tar.gz
          tar -xvf nginx-1.20.1.tar.gz
          cd nginx-1.20.1
          ./configure --prefix=/usr --with-http_ssl_module --with-http_v2_module --with-stream
          make

      - name: Build RPM
        run: |
          cd nginx-1.20.1
          sudo checkinstall --pkgname=nginx --pkgversion=1.20.1 --pkgrelease=1.el8 --default

      - name: Upload RPM package
        uses: actions/upload-artifact@v2
        with:
          name: nginx-rpm
          path: /workspace/nginx-1.20.1-1.el8.x86_64.rpm
