name: Build NGINX on ubuntu-22.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Use a CentOS 8 runner

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install -y gcc libpcre3 libpcre3-dev  zlib1g-dev openssl libssl-dev

      - name: Download and build NGINX
        run: |
          curl -O http://nginx.org/download/nginx-1.20.1.tar.gz
          tar -xvf nginx-1.20.1.tar.gz
          cd nginx-1.20.1
          ./configure --prefix=/usr 
          make
          sudo make install DESTDIR=/nginx-install
          cd /nginx-install
          sudo mkdir nginx-1.20.1
          sudo cp -r * nginx-1.20.1/ --exclude='./nginx-1.20.1'
          sudo tar -czvf nginx-1.20.1.tar.gz nginx-1.20.1
        
      - name: Upload NGINX tar.gz package
        uses: actions/upload-artifact@v3
        with:
          name: nginx-tarball
          path: nginx-install/nginx-1.20.1.tar.gz
          
