name: Build NGINX RPM on CentOS 8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev

      - name: Download NGINX source and prepare for RPM build
        run: |
          curl -O http://nginx.org/download/nginx-1.20.1.tar.gz
          tar -xvf nginx-1.20.1.tar.gz
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          mv nginx-1.20.1.tar.gz ~/rpmbuild/SOURCES/

      - name: Create NGINX spec file
        run: |
          cat <<EOL > ~/rpmbuild/SPECS/nginx.spec
          Name: nginx
          Version: 1.20.1
          Release: 1%{?dist}
          Summary: NGINX web server
          License: BSD
          Source0: nginx-1.20.1.tar.gz

          BuildRequires: gcc, make, pcre-devel, zlib-devel, openssl-devel
          Requires: pcre, zlib, openssl

          %description
          NGINX is a high-performance web server.

          %prep
          %setup -q

          %build
          ./configure --prefix=/usr --with-http_ssl_module --with-http_v2_module --with-stream
          make

          %install
          rm -rf %{buildroot}
          make DESTDIR=%{buildroot} install

          %files
          /usr/sbin/nginx
          /etc/nginx

          %changelog
          * Thu Nov 02 2024 Your Name <your.email@example.com> - 1.20.1-1
          - Initial package
          EOL

      - name: Build RPM
        run: |
          rpmbuild -bb ~/rpmbuild/SPECS/nginx.spec

      - name: Upload RPM package
        uses: actions/upload-artifact@v3
        with:
          name: nginx-rpm
          path: ~/rpmbuild/RPMS/x86_64/*.rpm
